### PR TITLE
Enable UTS

### PR DESCRIPTION
**Pull request by sergey-levin**
For sailjail working on emulator, kernel need to support UTS.

### CODE REVIEW

**Review by Thaodan — CHANGES_REQUESTED** [review]
Please add the reason to the commit message. 

Is there a bugref for this?

**Comment by sergey-levin** [comment]
# Description

For sailjail working on emulator, kernel need to support UTS.

# Explanation

In this code https://github.com/sailfishos-mirror/firejail/blob/0.9.64.4/src/firejail/main.c#L2919-L2952 the clone procedure exits with error code EINVAL.
From clone (https://man7.org/linux/man-pages/man2/clone.2.html) manual:
> EINVAL CLONE_NEWUTS was specified in the flags mask, but the kernel was not configured with the CONFIG_UTS_NS option.

# Solution

Running clone procedure with flags that contain CLONE_NEWUTS require UTS support in kernel.

PS From here: https://bz.jollamobile.com/show_bug.cgi?id=54895

**Comment by Thaodan** [comment]
To the commit message not the PR. Look at the other PRs.

**Comment by sergey-levin** [comment]
Done.

**Comment by sergey-levin** [comment]
Done.

**Comment by saukko** [comment]
Hmmp.... has anyone ran https://github.com/mer-hybris/mer-kernel-check/blob/master/mer_verify_kernel_config through with this kernel? Just pondering what else we might be missing on it?

**Comment by sergey-levin** [comment]
> Hmmp.... has anyone ran https://github.com/mer-hybris/mer-kernel-check/blob/master/mer_verify_kernel_config through with this kernel? Just pondering what else we might be missing on it?

Nope. If I done it right:

[defaultuser@AuroraEmulator ~]$ sudo /usr/bin/mer_verify_kernel_config /boot/config-5.0.21-1.8.23.omp
ERROR: CONFIG_HOTPLUG is invalid
It is unset
Allowed values : y
[defaultuser@AuroraEmulator ~]$

**Review by okodron — APPROVED** [review]

**Review by Thaodan — APPROVED** [review]

**Comment by stanislavmaksimov** [comment]
@vigejolla, @martyone, @Thaodan, @saukko, could you please merge this PR

**Pull request merged**
