### PR TITLE
[sailfish] Enable iptables match options. JB#44783

### PR DESCRIPTION
**Pull request by ballock**

### CODE REVIEW

**Comment by LaakkonenJussi** [comment]
I’d suppose adding CONFIG_IP_DCCP and CONFIG_IP_SCTP would be required for those protocols to work (?).

**Comment by ballock** [comment]
When I I just stumbled over the lack of CONFIG_NETFILTER_XT_MATCH_QTAGUID. Looks like qtaguid match only exists in Android specific kernel tree, and is not upstream. Looking at https://blog.linuxplumbersconf.org/2017/ocw/sessions/4786.html I guess it is not even going to be upstreamed.

Now, the connman unit tests are going to fail for the x86-emul, since they are testing the owner match inside the input filter, and the (currently disabled) CONFIG_NETFILTER_XT_MATCH_OWNER only supports the output and postrouting chain. mer-kernel-check will also probably fail due to missing QTAGUID option.

Should we move the kernel to an Android tree? FYI: https://elinux.org/images/d/d6/Android_common_kernel_and_out_of_tree_patchset.pdf

**Comment by LaakkonenJussi** [comment]
Hmh, well that is bad. It means that when there is no Android kernel in use we should use the `CONFIG_NETFILTER_XT_MATCH_OWNER`, which from iptables point of view had a bit different functionality than this `CONFIG_NETFILTER_XT_MATCH_QTAGUID`. This kind of differences will create problems. Or should we patch all kernels with that QTAGUID support? Which one would be best in the long term?

**Comment by ballock** [comment]
I think we should use an Android stack kernel in the emulator.
Currently it's the only kernel that does not have the Android patches. Although SailfishOS does not require Android to run, but all devices being Android base is a fact, and having different environment in the emulator is a little weird.
I think there is more problems than just this one related to the emulator being different to real devices.
Even our only x86 device, the tablet, is an Android tree.

**Comment by LaakkonenJussi** [comment]
Luckily, iptables implementation we use in ConnMan can just discard rules that kernel states as invalid without any issues. So moving to Android stack kernel is not that mandatory thinking this particular issue. It would only mean that on devices where `CONFIG_NETFILTER_XT_MATCH_OWNER` is defined the use is quite limited to the devices where QTAGUID support is enabled.

**Comment by martyone** [comment]
@ballock please drop the [changelog] message from the commit, leave it just in the PR description

**Comment by martyone** [comment]
And rebase on updated master please

**Pull request merged**
